//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirstProject.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAbout
    {
        public int AboutID { get; set; }
        public string Descrption { get; set; }
        public string ImgeURL { get; set; }
        public Nullable<bool> Statu { get; set; }
    }
}
